### ISSUE TITLE
$(CREAT) = $(MODIF)

### ISSUE THREAD

**Issue by noddle6cocoon** [qarmin/szyszka#56] opened 2021-10-15 14:40 UTC
hello,

these two options appear to give the same result. creation date option does not appear to pull from metadata. 

**pdf metadata:**
![screenshot-2021-10-15-10-34](https://user-images.githubusercontent.com/85046965/137504864-b074127c-da02-4baf-9b4f-044d50753334.png)
---
**$(creat) result:** 
![screenshot-2021-10-15-10-37](https://user-images.githubusercontent.com/85046965/137505200-66df835c-1a7d-43f0-b3bc-b0a441a2390a.png)
---
**$(modif) result:** 
![screenshot-2021-10-15-10-37_1](https://user-images.githubusercontent.com/85046965/137505324-173e33ad-36ac-4fd9-a4c7-5cc29b92ddb4.png)
---

**Comment by qarmin** [comment] 2021-11-08 08:52
This should be fixed by https://github.com/qarmin/szyszka/commit/3eb9e32692250ce176fa7ea1aa43a3cbd8383fc1
I can't reproduce this issue with latest commit

**Closed by qarmin** 2021-11-08 08:52 UTC
